// oxlint-disable-next-line eslint/sort-keys
export const APP_IPC_CHANNELS = {
  chooseBackupForRestore: "app:chooseBackupForRestore",
  command: "app:command",
  clearData: "app:clearData",
  claimFocusTimerCycleCompletion: "app:claimFocusTimerCycleCompletion",
  claimFocusTimerLeadership: "app:claimFocusTimerLeadership",
  exportBackup: "app:exportBackup",
  exportCsvData: "app:exportCsvData",
  focusSessionRecorded: "app:focusSessionRecorded",
  focusTimerActionRequested: "app:focusTimerActionRequested",
  focusTimerShortcutStatusChanged: "app:focusTimerShortcutStatusChanged",
  focusTimerStateChanged: "app:focusTimerStateChanged",
  getDesktopNotificationStatus: "app:getDesktopNotificationStatus",
  getFocusTimerShortcutStatus: "app:getFocusTimerShortcutStatus",
  getLatestAutoBackupRestorePreview: "app:getLatestAutoBackupRestorePreview",
  importBackup: "app:importBackup",
  openAutoBackupFolder: "app:openAutoBackupFolder",
  openDataFolder: "app:openDataFolder",
  query: "app:query",
  releaseFocusTimerLeadership: "app:releaseFocusTimerLeadership",
  restoreBackup: "app:restoreBackup",
  resizeFocusWidget: "app:resizeFocusWidget",
  showFocusWidget: "app:showFocusWidget",
  showMainWindow: "app:showMainWindow",
  showNotification: "app:showNotification",
  windDownNavigationRequested: "app:windDownNavigationRequested",
} as const;
